# Generated by Django 5.2.5 on 2025-10-07 08:00

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0007_remove_departamento_funcionarios_departamento_local'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('categoria', models.CharField(max_length=100)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Competência',
                'verbose_name_plural': 'Competências',
                'db_table': 'competencias',
            },
        ),
        migrations.CreateModel(
            name='Formacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('ONLINE', 'Online'), ('HIBRIDO', 'Híbrido'), ('EAD', 'EAD')], max_length=20)),
                ('categoria', models.CharField(max_length=100)),
                ('carga_horaria', models.IntegerField()),
                ('vagas', models.IntegerField()),
                ('vagas_disponiveis', models.IntegerField()),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('horario', models.CharField(max_length=100)),
                ('local', models.CharField(blank=True, max_length=200)),
                ('link_online', models.URLField(blank=True)),
                ('custo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('PLANEJADA', 'Planejada'), ('INSCRICOES_ABERTAS', 'Inscrições Abertas'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='PLANEJADA', max_length=20)),
                ('avaliacao_media', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('total_avaliacoes', models.IntegerField(default=0)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('competencias', models.ManyToManyField(blank=True, related_name='formacoes', to='formacoes.competencia')),
            ],
            options={
                'verbose_name': 'Formação',
                'verbose_name_plural': 'Formações',
                'db_table': 'formacoes',
            },
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADA', 'Aprovada'), ('REPROVADA', 'Reprovada'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=20)),
                ('prioridade', models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Média'), ('BAIXA', 'Baixa')], default='MEDIA', max_length=10)),
                ('justificativa', models.TextField()),
                ('motivo_reprovacao', models.TextField(blank=True)),
                ('aprovador', models.CharField(blank=True, max_length=200)),
                ('data_inscricao', models.DateTimeField(auto_now_add=True)),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True)),
                ('formacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='formacoes.formacao')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes_formacoes', to='app.funcionario')),
            ],
            options={
                'verbose_name': 'Inscrição',
                'verbose_name_plural': 'Inscrições',
                'db_table': 'inscricoes_formacoes',
                'unique_together': {('formacao', 'funcionario')},
            },
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('data_emissao', models.DateField(auto_now_add=True)),
                ('data_validade', models.DateField(blank=True, null=True)),
                ('arquivo', models.FileField(blank=True, upload_to='certificados/')),
                ('inscricao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificado', to='formacoes.inscricao')),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
                'db_table': 'certificados_formacoes',
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoFormacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nota_conteudo', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('nota_instrutor', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('nota_material', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('nota_organizacao', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('nota_geral', models.DecimalField(decimal_places=2, max_digits=3)),
                ('comentario', models.TextField(blank=True)),
                ('recomendaria', models.BooleanField(default=True)),
                ('data_avaliacao', models.DateTimeField(auto_now_add=True)),
                ('inscricao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacao', to='formacoes.inscricao')),
            ],
            options={
                'verbose_name': 'Avaliação de Formação',
                'verbose_name_plural': 'Avaliações de Formações',
                'db_table': 'avaliacoes_formacoes',
            },
        ),
        migrations.CreateModel(
            name='Instrutor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=10)),
                ('especialidade', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('certificacoes', models.JSONField(default=list)),
                ('biografia', models.TextField(blank=True)),
                ('avaliacao_media', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('total_formacoes', models.IntegerField(default=0)),
                ('total_alunos', models.IntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.funcionario')),
            ],
            options={
                'verbose_name': 'Instrutor',
                'verbose_name_plural': 'Instrutores',
                'db_table': 'instrutores',
            },
        ),
        migrations.AddField(
            model_name='formacao',
            name='instrutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formacoes', to='formacoes.instrutor'),
        ),
        migrations.CreateModel(
            name='AvaliacaoCompetencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nivel_atual', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('nivel_desejado', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('gap', models.IntegerField()),
                ('avaliador', models.CharField(max_length=200)),
                ('data_avaliacao', models.DateField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_competencias', to='app.funcionario')),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='formacoes.competencia')),
            ],
            options={
                'verbose_name': 'Avaliação de Competência',
                'verbose_name_plural': 'Avaliações de Competências',
                'db_table': 'avaliacoes_competencias',
                'unique_together': {('funcionario', 'competencia', 'data_avaliacao')},
            },
        ),
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('presente', models.BooleanField(default=False)),
                ('observacao', models.TextField(blank=True)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='formacoes.inscricao')),
            ],
            options={
                'verbose_name': 'Presença',
                'verbose_name_plural': 'Presenças',
                'db_table': 'presencas_formacoes',
                'unique_together': {('inscricao', 'data')},
            },
        ),
    ]
