# Generated by Django 5.2.5 on 2025-09-20 09:29

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('etapa', models.CharField(choices=[('triagem', 'Triagem'), ('entrevista', 'Entrevista'), ('teste', 'Teste Técnico'), ('contratado', 'Contratado'), ('rejeitado', 'Rejeitado')], default='triagem', max_length=10)),
                ('dataInscricao', models.DateTimeField(auto_now_add=True)),
                ('curriculum', models.FileField(upload_to='curriculos/')),
                ('score', models.IntegerField(default=0)),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('nif', models.CharField(max_length=14, unique=True)),
                ('email_corporativo', models.EmailField(max_length=254, unique=True)),
                ('tipo_empresa', models.CharField(blank=True, max_length=50, null=True)),
                ('setor_atuacao', models.CharField(blank=True, max_length=100, null=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioEmpresa',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nomeRep', models.CharField(blank=True, max_length=255, null=True)),
                ('nivel_acesso', models.CharField(choices=[('admin', 'Administrador'), ('funcionario', 'Funcionario')], default='admin', max_length=20)),
                ('emailRep', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.empresa')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Dispensas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('inicio', models.DateField()),
                ('fim', models.DateField()),
                ('justificativo', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=10)),
                ('admin_comentario', models.TextField(blank=True)),
                ('por', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='DescontosImposto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desconto_inss', models.DecimalField(decimal_places=2, default=0.03, max_digits=10)),
                ('irt2', models.DecimalField(decimal_places=2, default=0.1, max_digits=10)),
                ('irt3', models.DecimalField(decimal_places=2, default=0.13, max_digits=10)),
                ('irt4', models.DecimalField(decimal_places=2, default=0.16, max_digits=10)),
                ('irt5', models.DecimalField(decimal_places=2, default=0.18, max_digits=10)),
                ('irt6', models.DecimalField(decimal_places=2, default=0.19, max_digits=10)),
                ('irt7', models.DecimalField(decimal_places=2, default=0.2, max_digits=10)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('responsavel', models.CharField(blank=True, default='Tana', max_length=40, null=True)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('orcamento', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('funcionarios', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='CamposPersonalizados',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(blank=True, choices=[('texto_curto', 'Texto Curto'), ('text', 'Texto Longo'), ('number', 'Número'), ('date', 'Data'), ('booleano', 'Sim/Não'), ('escolha_unica', 'Escolha Única'), ('select', 'Múltipla Escolha'), ('file', 'Arquivo'), ('email', 'Email'), ('telefone', 'Telefone')], max_length=50, null=True)),
                ('obrigatorio', models.BooleanField(default=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='FolhaPagamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(default='Tana', max_length=100)),
                ('mes_referencia', models.DateField()),
                ('salario_bruto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desconto_inss', models.DecimalField(decimal_places=2, default=0.03, max_digits=10)),
                ('desconto_irt', models.DecimalField(decimal_places=2, default=0.1, max_digits=10)),
                ('salario_liquido', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('descontos', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Formacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('area_tematica', models.CharField(max_length=100)),
                ('Carga_horaria', models.CharField(max_length=15)),
                ('horario', models.CharField(default='10-14H', max_length=15)),
                ('modalidade', models.CharField(max_length=20)),
                ('dataInicio', models.DateField()),
                ('dataFim', models.DateField()),
                ('descricao', models.TextField(default='O curso deve ser feito')),
                ('local', models.CharField(max_length=100)),
                ('Formadores', models.CharField(max_length=200)),
                ('vagas', models.IntegerField(blank=True, null=True)),
                ('empresaParceira', models.CharField(blank=True, max_length=200, null=True)),
                ('inscritos', models.IntegerField(blank=True, null=True)),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.departamento')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('terminadado', 'Terminadado')], default='pendente', max_length=20)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.empresa')),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Inscrito', to=settings.AUTH_USER_MODEL)),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.formacoes')),
            ],
        ),
        migrations.CreateModel(
            name='Modulos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.JSONField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=6)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usado', models.BooleanField(default=False)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Vagas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('requisitos', models.TextField()),
                ('dataAbertura', models.DateField()),
                ('dataFim', models.DateField()),
                ('tipoVaga', models.CharField(choices=[('tempoIntegral', 'Tempo Integral'), ('remoto', 'Remoto'), ('meioPeriodo', 'Meio Período')], default='tempoIntegral', max_length=30)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('fechada', 'Fechada')], default='aberta', max_length=10)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.departamento')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='TesteTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('dataLimite', models.DateTimeField()),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.candidato')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vagas')),
            ],
        ),
        migrations.CreateModel(
            name='Entrevista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataHora', models.DateTimeField()),
                ('local', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.candidato')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vagas')),
            ],
        ),
        migrations.AddField(
            model_name='candidato',
            name='vaga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatos', to='app.vagas'),
        ),
        migrations.CreateModel(
            name='Valores',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('valores', models.JSONField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.departamento')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.empresa')),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ValoresArquivo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('arquivo', models.FileField(upload_to='arquivos/')),
                ('campo_personalizado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.campospersonalizados')),
                ('valores_instancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='app.valores')),
            ],
        ),
    ]
