# Generated by Django 5.2.5 on 2025-09-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_satisfacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='satisfacao',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
