# Generated by Django 5.2.5 on 2025-10-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_satisfacao_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='vagas',
            name='beneficios',
            field=models.CharField(default='Nenhum', max_length=30),
        ),
        migrations.AddField(
            model_name='vagas',
            name='cidade',
            field=models.CharField(default='Luanda', max_length=40),
        ),
        migrations.AddField(
            model_name='vagas',
            name='descricao_vaga',
            field=models.TextField(default='Qualificado'),
        ),
        migrations.AddField(
            model_name='vagas',
            name='modalidade',
            field=models.CharField(default='Presencial', max_length=40),
        ),
        migrations.AddField(
            model_name='vagas',
            name='nivel',
            field=models.CharField(default='Pleno', max_length=40),
        ),
        migrations.AddField(
            model_name='vagas',
            name='requisitos_desejavel',
            field=models.TextField(default='requisito_desejavel'),
        ),
        migrations.AddField(
            model_name='vagas',
            name='requisitos_obrigatorio',
            field=models.TextField(default='requisitos_obrigatorio'),
        ),
        migrations.AddField(
            model_name='vagas',
            name='salario_min',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='vagas',
            name='tipo_contrato',
            field=models.CharField(default='Estágio', max_length=30),
        ),
        migrations.AddField(
            model_name='vagas',
            name='vaga_limite',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='vagas',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vagas',
            name='tipoVaga',
            field=models.CharField(max_length=40),
        ),
    ]
