# Generated by Django 5.2.5 on 2025-10-03 21:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_vagas_beneficios_vagas_cidade_vagas_descricao_vaga_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testetecnico',
            name='candidato',
        ),
        migrations.RemoveField(
            model_name='entrevista',
            name='candidato',
        ),
        migrations.RemoveField(
            model_name='descontosimposto',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='entrevista',
            name='vaga',
        ),
        migrations.RemoveField(
            model_name='folhapagamento',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='formacoes',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='formacoes',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='inscricao',
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='funcionario',
        ),
        migrations.RemoveField(
            model_name='modulos',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='testetecnico',
            name='vaga',
        ),
        migrations.RemoveField(
            model_name='vagas',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='vagas',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='valores',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='valores',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='valores',
            name='funcionario',
        ),
        migrations.AddField(
            model_name='departamento',
            name='codigo',
            field=models.CharField(default='TI', max_length=20),
        ),
        migrations.AddField(
            model_name='departamento',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('valores', models.JSONField()),
                ('salario_bruto', models.DecimalField(decimal_places=2, default='100.00', max_digits=10)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.departamento')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.empresa')),
            ],
        ),
        migrations.AlterField(
            model_name='valoresarquivo',
            name='valores_instancia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='app.funcionario'),
        ),
        migrations.DeleteModel(
            name='Candidato',
        ),
        migrations.DeleteModel(
            name='DescontosImposto',
        ),
        migrations.DeleteModel(
            name='Entrevista',
        ),
        migrations.DeleteModel(
            name='FolhaPagamento',
        ),
        migrations.DeleteModel(
            name='Formacoes',
        ),
        migrations.DeleteModel(
            name='Inscricao',
        ),
        migrations.DeleteModel(
            name='Modulos',
        ),
        migrations.DeleteModel(
            name='TesteTecnico',
        ),
        migrations.DeleteModel(
            name='Vagas',
        ),
        migrations.DeleteModel(
            name='Valores',
        ),
    ]
