# Generated by Django 5.2.5 on 2025-10-03 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_testetecnico_candidato_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='funcionarios',
        ),
        migrations.AddField(
            model_name='departamento',
            name='local',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
