# Generated by Django 5.2.5 on 2025-10-05 10:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aplicacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('NOVO', 'Novo'), ('TRIAGEM', 'Triagem'), ('TESTE', 'Teste'), ('ENTREVISTA', 'Entrevista'), ('PROPOSTA', 'Proposta'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado')], default='NOVO', max_length=20)),
                ('pontuacao', models.IntegerField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('data_aplicacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'aplicacoes',
                'ordering': ['-data_aplicacao'],
            },
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('linkedin', models.URLField(blank=True)),
                ('curriculo', models.FileField(blank=True, null=True, upload_to='curriculos/')),
                ('experiencia_anos', models.IntegerField(default=0)),
                ('formacao', models.CharField(blank=True, max_length=200)),
                ('habilidades', models.TextField(blank=True)),
                ('pretensao_salarial', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('disponibilidade', models.CharField(blank=True, max_length=100)),
                ('observacoes', models.TextField(blank=True)),
                ('fonte', models.CharField(blank=True, max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'candidatos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('departamento', models.CharField(max_length=100)),
                ('localizacao', models.CharField(max_length=200)),
                ('tipo_contrato', models.CharField(choices=[('CLT', 'CLT'), ('PJ', 'PJ'), ('ESTAGIO', 'Estágio'), ('TEMPORARIO', 'Temporário')], default='CLT', max_length=20)),
                ('salario_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salario_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('requisitos', models.TextField()),
                ('beneficios', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('EM_ANDAMENTO', 'Em Andamento'), ('PAUSADA', 'Pausada'), ('FECHADA', 'Fechada')], default='ABERTA', max_length=20)),
                ('vagas_disponiveis', models.IntegerField(default=1)),
                ('data_abertura', models.DateField(auto_now_add=True)),
                ('data_fechamento', models.DateField(blank=True, null=True)),
                ('responsavel', models.CharField(blank=True, max_length=200)),
                ('empresa', models.CharField(max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vagas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('TRIAGEM', 'Triagem'), ('TECNICA', 'Técnica'), ('COMPORTAMENTAL', 'Comportamental'), ('FINAL', 'Final')], max_length=20)),
                ('avaliador', models.CharField(max_length=200)),
                ('nota', models.IntegerField()),
                ('comentarios', models.TextField(blank=True)),
                ('criterios', models.JSONField(default=dict)),
                ('data_avaliacao', models.DateTimeField(auto_now_add=True)),
                ('aplicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='recrutamento.aplicacao')),
            ],
            options={
                'db_table': 'avaliacoes',
                'ordering': ['-data_avaliacao'],
            },
        ),
        migrations.AddField(
            model_name='aplicacao',
            name='candidato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicacoes', to='recrutamento.candidato'),
        ),
        migrations.CreateModel(
            name='Entrevista',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('TELEFONE', 'Telefone'), ('VIDEO', 'Vídeo'), ('PRESENCIAL', 'Presencial')], max_length=20)),
                ('entrevistador', models.CharField(max_length=200)),
                ('data_hora', models.DateTimeField()),
                ('duracao_minutos', models.IntegerField(default=60)),
                ('local', models.CharField(blank=True, max_length=200)),
                ('link_video', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('AGENDADA', 'Agendada'), ('REALIZADA', 'Realizada'), ('CANCELADA', 'Cancelada')], default='AGENDADA', max_length=20)),
                ('feedback', models.TextField(blank=True)),
                ('nota', models.IntegerField(blank=True, null=True)),
                ('aplicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrevistas', to='recrutamento.aplicacao')),
            ],
            options={
                'db_table': 'entrevistas',
                'ordering': ['data_hora'],
            },
        ),
        migrations.CreateModel(
            name='Teste',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('TECNICO', 'Técnico'), ('LOGICA', 'Lógica'), ('IDIOMA', 'Idioma'), ('PERSONALIDADE', 'Personalidade')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('link', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDO', 'Concluído'), ('EXPIRADO', 'Expirado')], default='PENDENTE', max_length=20)),
                ('nota', models.IntegerField(blank=True, null=True)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('prazo', models.DateTimeField(blank=True, null=True)),
                ('aplicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testes', to='recrutamento.aplicacao')),
            ],
            options={
                'db_table': 'testes',
                'ordering': ['-data_envio'],
            },
        ),
        migrations.AddField(
            model_name='candidato',
            name='vaga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidato', to='recrutamento.vaga'),
        ),
        migrations.AddField(
            model_name='aplicacao',
            name='vaga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicacoes', to='recrutamento.vaga'),
        ),
        migrations.AlterUniqueTogether(
            name='aplicacao',
            unique_together={('vaga', 'candidato')},
        ),
    ]
