# Generated by Django 5.2.5 on 2025-10-05 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_departamento_funcionarios_departamento_local'),
        ('recrutamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaga', to='app.departamento'),
        ),
    ]
