# Generated by Django 5.2.5 on 2025-10-06 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_departamento_funcionarios_departamento_local'),
        ('recrutamento', '0003_alter_vaga_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='empresa',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='candidato_empresa', to='app.empresa'),
        ),
    ]
