# Generated by Django 5.2.5 on 2025-10-06 10:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0007_remove_departamento_funcionarios_departamento_local'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], max_length=50)),
                ('descricao', models.TextField()),
                ('data', models.DateField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('resolvido', 'Resolvido'), ('ignorado', 'Ignorado')], default='pendente', max_length=50)),
                ('data_resolucao', models.DateTimeField(blank=True, null=True)),
                ('observacao_resolucao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.departamento')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='app.funcionario')),
                ('resolvido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_resolvidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'db_table': 'alerta',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='BiometriaFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('digital', 'Digital'), ('facial', 'Facial'), ('voz', 'Voz')], max_length=50)),
                ('dados_biometricos', models.TextField()),
                ('dispositivo', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometrias', to='app.funcionario')),
            ],
            options={
                'verbose_name': 'Biometria do Funcionário',
                'verbose_name_plural': 'Biometrias dos Funcionários',
                'db_table': 'biometria_funcionario',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('entrada', models.TimeField()),
                ('saida', models.TimeField()),
                ('intervalo_inicio', models.TimeField(blank=True, null=True)),
                ('intervalo_fim', models.TimeField(blank=True, null=True)),
                ('tolerancia_entrada', models.IntegerField(default=15)),
                ('tolerancia_saida', models.IntegerField(default=15)),
                ('dias_semana', models.JSONField(default=list)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='app.empresa')),
            ],
            options={
                'verbose_name': 'Horário',
                'verbose_name_plural': 'Horários',
                'db_table': 'horario',
            },
        ),
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('fixa', 'Fixa'), ('rotativa', 'Rotativa'), ('flexivel', 'Flexível')], max_length=50)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalas', to='app.empresa')),
                ('funcionarios', models.ManyToManyField(related_name='escalas', to='app.funcionario')),
                ('horario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalas', to='assiduidade.horario')),
            ],
            options={
                'verbose_name': 'Escala',
                'verbose_name_plural': 'Escalas',
                'db_table': 'escala',
            },
        ),
        migrations.CreateModel(
            name='Justificativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('falta', 'Falta'), ('atraso', 'Atraso'), ('saida_antecipada', 'Saída Antecipada')], max_length=50)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('motivo', models.TextField()),
                ('documento', models.FileField(blank=True, null=True, upload_to='justificativas/')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=50)),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True)),
                ('observacao_aprovador', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aprovador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='justificativas_aprovadas', to=settings.AUTH_USER_MODEL)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justificativas', to='app.funcionario')),
            ],
            options={
                'verbose_name': 'Justificativa',
                'verbose_name_plural': 'Justificativas',
                'db_table': 'justificativa',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='RegistroPonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída'), ('saida_intervalo', 'Saída Intervalo'), ('retorno_intervalo', 'Retorno Intervalo')], max_length=50)),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('localizacao', models.CharField(blank=True, max_length=200, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('biometria_validada', models.BooleanField(default=False)),
                ('dispositivo', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('sucesso', 'Sucesso'), ('pendente', 'Pendente'), ('rejeitado', 'Rejeitado')], default='sucesso', max_length=50)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('biometria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assiduidade.biometriafuncionario')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_ponto', to='app.funcionario')),
            ],
            options={
                'verbose_name': 'Registro de Ponto',
                'verbose_name_plural': 'Registros de Ponto',
                'db_table': 'registro_ponto',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='BancoHoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('tipo', models.CharField(choices=[('credito', 'Crédito'), ('debito', 'Débito'), ('compensacao', 'Compensação')], max_length=50)),
                ('horas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('descricao', models.TextField()),
                ('saldo_anterior', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('saldo_atual', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('aprovado', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aprovador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banco_horas_aprovadas', to=settings.AUTH_USER_MODEL)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banco_horas', to='app.funcionario')),
                ('registro_ponto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assiduidade.registroponto')),
            ],
            options={
                'verbose_name': 'Banco de Horas',
                'verbose_name_plural': 'Banco de Horas',
                'db_table': 'banco_horas',
                'ordering': ['-data'],
            },
        ),
    ]
