from django.urls import path
from .logica import (CadastrarEmpresa,solicitar_recuperacao_senha,enviar_email_recuperacao,verificar_codigo_recuperacao,enviar_email_senha_alterada,redefinir_senha, Login, usuario_logado,usuario_detail,usuario_list,set_password,verificar_otp)
from .views import (campos,empresa,campos_empresa,
valoresdoscampos,percentagemSatisfacao,campo_detalhe,campos_empresa_com_uso,satisfacao,DepartamentoView,deletar,
criar_dispensa,
todo_dispensa,
campos_lista, 
minha_dispensa,logout_view,
perfil_funcionario,
ActualizarAPIView)
from rest_framework_simplejwt.views import TokenRefreshView
from . import views_admin
urlpatterns=[
    path('empresa/', CadastrarEmpresa.as_view(),name="Empresa" ),
    path('usuario/',usuario_list, name="usuarios"),
    path('campos/criar/', campos, name="criar_campos"),
    path('satisfacao/', percentagemSatisfacao, name="satis"),
    path('satisfacao/criar/', satisfacao.as_view(), name="criar_satisfacao"),
    path('campos/empresa/com-uso/', campos_empresa_com_uso, name='campos-empresa-com-uso'),
    path('campos/<str:pk>/', campo_detalhe, name='campo-detalhe'),
    path('campos/', campos_lista, name="lista_campos"),
    path('campos/empresa/', campos_empresa, name="campos"),
    path('refresh/',TokenRefreshView.as_view(), name="refresh"),
    path('usuariologado/', usuario_logado, name="usuariologado"),
    path('valores/', valoresdoscampos.as_view(), name="valores"),
    path('login/', Login.as_view(), name='login'),
    path('departamentos/', DepartamentoView.as_view(), name="departamentos"),
    path('logout/', logout_view, name="logout"),
    path('empresa', empresa, name="empresa"),
    path('valores/<str:pk>/', valoresdoscampos.as_view(), name='valores-detail'),
    path('usuario_detail/<str:pk>/', usuario_detail, name='v'),
    path('perfil/',perfil_funcionario,name="perfil"),
    path('set-password/', set_password, name="setsenha"),
    path('verifcar-otp/', verificar_otp, name="verificar"),
    path('dispensas/criar/', criar_dispensa, name="ver"),
    path('dispensa/my/',minha_dispensa, name="dispensas"),
    path('dispensa/todas/',todo_dispensa, name="todo_dispensa"),
    path('actualizar/<int:id>/',ActualizarAPIView, name="a"),
    path('deletar-dispensa/<int:pk>/',deletar,name="deleta" ),
    path('metricas-gerais/', views_admin.metricas_gerais, name='metricas-gerais'),
    path('alertas-pendencias/', views_admin.alertas_pendencias, name='alertas-pendencias'),
    path('evolucao-geral/', views_admin.evolucao_geral, name='evolucao-geral'),
    path('atividades-recentes/', views_admin.atividades_recentes, name='atividades-recentes'),
    path('solicitar-recuperacao-senha/', solicitar_recuperacao_senha, name='solicitar-recuperacao-senha'),
    path('verificar-codigo-recuperacao/',verificar_codigo_recuperacao, name='verificar-codigo-recuperacao'),
    path('redefinir-senha/', redefinir_senha, name='redefinir-senha'),
]