from django.urls import path
from .views import (CadastrarEmpresa, ususario,campos,campos_empresa,listar_vagas_por_empresa,
VagasView,valoresdoscampos,PainelDados,DepartamentoView,set_password,deletar,
verificar_otp,InscricoesView,DescontoImpostos,criar_dispensa,EntrevistaView,
TesteTecnicoView,ResumoFolhaView,HistoricoFolhaView,RelatorioView
,formacores_departamento,formacores_data,DescontosImpostoView,
FolhaPagamentoView,todo_dispensa,
campos_lista,Login, ModulosView, usuario_logado, CandidaturaView,
candidatosView,minha_dispensa,logout_view,FormacoesView,
ProximasEntrevistasView,perfil_funcionario,
ActualizarAPIView,minha_formacoes)
from rest_framework_simplejwt.views import TokenRefreshView

urlpatterns=[
    path('empresa/', CadastrarEmpresa.as_view(),name="Empresa" ),
    path('usuario/',ususario, name="usuarios"),
    path('campos/criar/', campos, name="criar_campos"),
    path('campos/', campos_lista, name="lista_campos"),
    path('campos/empresa/', campos_empresa, name="campos"),
    path('modulos/', ModulosView.as_view(), name="modulos"),
    path('refresh/',TokenRefreshView.as_view(), name="refresh"),
    path('usuariologado/', usuario_logado, name="usuariologado"),
    path('valores/', valoresdoscampos.as_view(), name="valores"),
    path('login/', Login.as_view(), name='login'),
    path('departamentos/', DepartamentoView.as_view(), name="departamentos"),
    path('actualizar/desconto/', DescontoImpostos.as_view(), name="descontos"),
    path('pagamentos/', FolhaPagamentoView.as_view(), name="pagamentos"),
    path('painel/', PainelDados.as_view(), name="painel"),
    path('vaga/', VagasView.as_view(), name="painel"),
    path('empresas/',listar_vagas_por_empresa, name="empresas"),
    path('Candidatura/',CandidaturaView.as_view(), name="candidatura"),
    path('Candidatos/',candidatosView, name="candidatos"),
    path('logout/', logout_view, name="logout"),
    path('formacoes/',FormacoesView.as_view(),name="formacao"),
    path('inscricao/',InscricoesView.as_view(),name="inscricao"),
    path('perfil/',perfil_funcionario,name="perfil"),
    path('set-password/', set_password, name="setsenha"),
    path('verifcar-otp/', verificar_otp, name="verificar"),
    path('dispensas/criar/', criar_dispensa, name="ver"),
    path('dispensa/my/',minha_dispensa, name="dispensas"),
    path('dispensa/todas/',todo_dispensa, name="todo_dispensa"),
    path('actualizar/<int:id>/',ActualizarAPIView, name="a"),
    path('deletar-dispensa/<int:pk>/',deletar,name="deleta" ),
    path('formacoes_departamento/',formacores_departamento, name="formacores_departamento"),
    path('formacoes_data/',formacores_data, name="formacores_departamento"),
    path('minha_formacoes/',minha_formacoes, name="forma"),
    path('entrevistas/', EntrevistaView.as_view(), name='entrevistas'),
    path('testes-tecnicos/', TesteTecnicoView.as_view(), name='testes_tecnicos'),
    path('relatorios/', RelatorioView.as_view(), name='relatorios'),
    path('entrevistas/proximas/',ProximasEntrevistasView.as_view(),name="proxima"),
    path('historico-folha/',HistoricoFolhaView.as_view(),name="historico-folha"),
    path('resumo-folha/',ResumoFolhaView.as_view() ,name="historico-folha"),
    path('descontos-imposto/',DescontosImpostoView.as_view(),name="descontos-imposto")
        
]