# Generated by Django 5.2 on 2025-08-08 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_formacoes_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='formacoes',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.departamento'),
        ),
    ]
