# Generated by Django 5.2 on 2025-08-08 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_formacoes_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='funcionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Inscrito', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='estado',
            field=models.BooleanField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('terminadado', 'Terminadado')], default='pendente'),
        ),
    ]
