# Generated by Django 5.2 on 2025-08-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_inscricao_funcionario_alter_inscricao_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='formacoes',
            name='vagas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='estado',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('terminadado', 'Terminadado')], default='pendente', max_length=20),
        ),
    ]
