# Generated by Django 5.2 on 2025-08-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_formacoes_vagas_alter_inscricao_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='formacoes',
            name='inscritos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
