# Generated by Django 5.2.5 on 2025-10-04 07:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_departamento_funcionarios_departamento_local'),
        ('folha_pagamento', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do benefício', max_length=100)),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada do benefício')),
                ('tipo', models.CharField(choices=[('FIXO', 'Valor Fixo'), ('PERCENTUAL', 'Percentual'), ('VARIAVEL', 'Variável')], default='FIXO', max_length=20)),
                ('categoria', models.CharField(choices=[('ALIMENTACAO', 'Vale Alimentação'), ('TRANSPORTE', 'Vale Transporte'), ('SAUDE', 'Plano de Saúde'), ('EDUCACAO', 'Auxílio Educação'), ('MORADIA', 'Auxílio Moradia'), ('OUTROS', 'Outros Benefícios')], default='OUTROS', max_length=20)),
                ('aplicavel_a', models.CharField(choices=[('TODOS', 'Todos os Funcionários'), ('DEPARTAMENTO', 'Por Departamento'), ('CARGO', 'Por Cargo'), ('INDIVIDUAL', 'Individual')], default='TODOS', max_length=20)),
                ('valor_fixo', models.DecimalField(decimal_places=2, default=0, help_text='Valor fixo do benefício (se tipo=FIXO)', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('percentual', models.DecimalField(decimal_places=2, default=0, help_text='Percentual do benefício (se tipo=PERCENTUAL)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('valor_minimo', models.DecimalField(decimal_places=2, default=0, help_text='Valor mínimo do benefício', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('valor_maximo', models.DecimalField(decimal_places=2, default=0, help_text='Valor máximo do benefício', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('descontavel_ir', models.BooleanField(default=False, help_text='Descontável do Imposto de Renda')),
                ('descontavel_inss', models.BooleanField(default=False, help_text='Descontável do INSS')),
                ('tributavel', models.BooleanField(default=False, help_text='Benefício tributável')),
                ('data_inicio', models.DateField(help_text='Data de início da vigência')),
                ('data_fim', models.DateField(blank=True, help_text='Data de fim da vigência (opcional)', null=True)),
                ('recorrente', models.BooleanField(default=True, help_text='Benefício recorrente mensalmente')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('SUSPENSO', 'Suspenso'), ('EXPIRADO', 'Expirado')], default='ATIVO', max_length=15)),
                ('ativo', models.BooleanField(default=True, help_text='Benefício ativo no sistema')),
                ('departamento_alvo', models.CharField(blank=True, help_text='Departamento alvo', max_length=100)),
                ('cargo_alvo', models.CharField(blank=True, help_text='Cargo alvo', max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('funcionario', models.ForeignKey(blank=True, help_text='Funcionário específico (se aplicavel_a=INDIVIDUAL)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beneficios', to='app.funcionario')),
            ],
            options={
                'verbose_name': 'Benefício',
                'verbose_name_plural': 'Benefícios',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['status', 'ativo'], name='folha_pagam_status_b364c8_idx'), models.Index(fields=['data_inicio', 'data_fim'], name='folha_pagam_data_in_2c6c06_idx'), models.Index(fields=['tipo', 'categoria'], name='folha_pagam_tipo_d3851d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Desconto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do desconto', max_length=100)),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada do desconto')),
                ('tipo', models.CharField(choices=[('FIXO', 'Valor Fixo'), ('PERCENTUAL', 'Percentual'), ('VARIAVEL', 'Variável')], default='FIXO', max_length=20)),
                ('categoria', models.CharField(choices=[('OBRIGATORIO', 'Desconto Obrigatório'), ('OPCIONAL', 'Desconto Opcional'), ('JUDICIAL', 'Desconto Judicial'), ('EMPRESTIMO', 'Empréstimo'), ('ADIANTO', 'Adiantamento'), ('OUTROS', 'Outros Descontos')], default='OPCIONAL', max_length=20)),
                ('aplicavel_a', models.CharField(choices=[('TODOS', 'Todos os Funcionários'), ('DEPARTAMENTO', 'Por Departamento'), ('CARGO', 'Por Cargo'), ('INDIVIDUAL', 'Individual')], default='TODOS', max_length=20)),
                ('valor_fixo', models.DecimalField(decimal_places=2, default=0, help_text='Valor fixo do desconto (se tipo=FIXO)', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('percentual', models.DecimalField(decimal_places=2, default=0, help_text='Percentual do desconto (se tipo=PERCENTUAL)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('valor_minimo', models.DecimalField(decimal_places=2, default=0, help_text='Valor mínimo do desconto', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('valor_maximo', models.DecimalField(decimal_places=2, default=0, help_text='Valor máximo do desconto', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('data_inicio', models.DateField(help_text='Data de início da vigência')),
                ('data_fim', models.DateField(blank=True, help_text='Data de fim da vigência (opcional)', null=True)),
                ('recorrente', models.BooleanField(default=False, help_text='Desconto recorrente mensalmente')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('SUSPENSO', 'Suspenso'), ('EXPIRADO', 'Expirado')], default='ATIVO', max_length=15)),
                ('ativo', models.BooleanField(default=True, help_text='Desconto ativo no sistema')),
                ('departamento_alvo', models.CharField(blank=True, help_text='Departamento alvo', max_length=100)),
                ('cargo_alvo', models.CharField(blank=True, help_text='Cargo alvo', max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('funcionario', models.ForeignKey(blank=True, help_text='Funcionário específico (se aplicavel_a=INDIVIDUAL)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descontos', to='app.funcionario')),
            ],
            options={
                'verbose_name': 'Desconto',
                'verbose_name_plural': 'Descontos',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['status', 'ativo'], name='folha_pagam_status_9e988e_idx'), models.Index(fields=['data_inicio', 'data_fim'], name='folha_pagam_data_in_ce1a36_idx'), models.Index(fields=['tipo', 'categoria'], name='folha_pagam_tipo_f077b4_idx')],
            },
        ),
    ]
