# Generated by Django 5.2.5 on 2025-10-04 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folha_pagamento', '0002_beneficio_desconto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibopagamento',
            name='mes_referencia',
            field=models.IntegerField(),
        ),
    ]
