# Generated by Django 5.2.5 on 2025-10-04 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folha_pagamento', '0003_alter_recibopagamento_mes_referencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibopagamento',
            name='ano_preferencia',
            field=models.IntegerField(default=2025),
        ),
    ]
