# Generated by Django 5.2.5 on 2025-10-04 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folha_pagamento', '0004_recibopagamento_ano_preferencia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recibopagamento',
            old_name='ano_preferencia',
            new_name='ano_referencia',
        ),
    ]
