# Generated by Django 5.2.5 on 2025-10-07 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_departamento_funcionarios_departamento_local'),
        ('folha_pagamento', '0005_rename_ano_preferencia_recibopagamento_ano_referencia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='descontosimposto',
            options={'verbose_name': 'Configuração de Impostos Angola', 'verbose_name_plural': 'Configurações de Impostos Angola'},
        ),
        migrations.RemoveField(
            model_name='descontosimposto',
            name='desconto_inss',
        ),
        migrations.RemoveField(
            model_name='descontosimposto',
            name='irt2',
        ),
        migrations.RemoveField(
            model_name='descontosimposto',
            name='irt3',
        ),
        migrations.RemoveField(
            model_name='descontosimposto',
            name='irt4',
        ),
        migrations.RemoveField(
            model_name='descontosimposto',
            name='irt5',
        ),
        migrations.RemoveField(
            model_name='descontosimposto',
            name='irt6',
        ),
        migrations.RemoveField(
            model_name='descontosimposto',
            name='irt7',
        ),
        migrations.AddField(
            model_name='descontosimposto',
            name='empresa',
            field=models.ForeignKey(default='37f1f5d0-4a49-4365-b8b2-beb988da968c', on_delete=django.db.models.deletion.CASCADE, to='app.empresa'),
        ),
        migrations.AddField(
            model_name='descontosimposto',
            name='inss_empresa_percent',
            field=models.DecimalField(decimal_places=2, default=8.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='descontosimposto',
            name='inss_trabalhador_percent',
            field=models.DecimalField(decimal_places=2, default=3.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='descontosimposto',
            name='irt_escalao_1',
            field=models.DecimalField(decimal_places=2, default=70000, max_digits=10),
        ),
        migrations.AddField(
            model_name='descontosimposto',
            name='irt_escalao_2_max',
            field=models.DecimalField(decimal_places=2, default=100000, max_digits=10),
        ),
        migrations.AddField(
            model_name='descontosimposto',
            name='irt_escalao_2_min',
            field=models.DecimalField(decimal_places=2, default=70000, max_digits=10),
        ),
        migrations.AddField(
            model_name='descontosimposto',
            name='irt_escalao_2_percent',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='descontosimposto',
            name='subsidio_alimentacao_minimo',
            field=models.DecimalField(decimal_places=2, default=35000, max_digits=10),
        ),
        migrations.AddField(
            model_name='descontosimposto',
            name='subsidio_transporte_minimo',
            field=models.DecimalField(decimal_places=2, default=25000, max_digits=10),
        ),
        migrations.AddField(
            model_name='descontosimposto',
            name='tipo_imposto',
            field=models.CharField(choices=[('IRT', 'Imposto sobre o Rendimento do Trabalho'), ('INSS', 'Instituto Nacional de Segurança Social'), ('AGT', 'Administração Geral Tributária')], default=None, max_length=10),
        ),
    ]
